// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoP2.database;

#nullable disable

namespace ProjetoP2.Migrations
{
    [DbContext(typeof(ProjetoP2DbContext))]
    partial class ProjetoP2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

<<<<<<< HEAD
            modelBuilder.Entity("ProjetoP2.Models.Administrador", b =>
=======
            modelBuilder.Entity("ProjetoP2.Models.Usuario", b =>
>>>>>>> a882809561136a2b1b99f52c9dc2c1ff33ca0b34
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

<<<<<<< HEAD
=======
                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

>>>>>>> a882809561136a2b1b99f52c9dc2c1ff33ca0b34
                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

<<<<<<< HEAD
                    b.ToTable("administradores");
                });

            modelBuilder.Entity("ProjetoP2.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeCliente")
                        .IsUnique();

                    b.ToTable("clientes");
=======
                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("usuarios");
>>>>>>> a882809561136a2b1b99f52c9dc2c1ff33ca0b34
                });
#pragma warning restore 612, 618
        }
    }
}
